name: jcheminf-dimensionality
channels:
  - conda-forge
dependencies:
  - python=3.12.11
  - numpy=1.26.4
  - pandas=2.3.2
  - scipy=1.16.2
  - matplotlib=3.10.6
  - rdkit=2025.03.6
  - scikit-learn=1.7.2
  - pip
