#!/usr/bin/env python3
"""Equivalence-margin sensitivity curve for the residual-minus-absolute ranking contrast.

Reviewer point (Major Revision, cross-lab review).  The Results text asserted a
*prespecified* symmetric equivalence margin of +/-0.03 while the Methods section of the
same manuscript states that equivalence readings are post hoc and that the 0.02/0.05
margins "are not interpreted as prospectively specified tests".  That is a flat
contradiction.  The margin is being relabelled post hoc, and a single threshold is
replaced by the whole sensitivity curve.

This script is a read-and-tabulate job.  It re-runs no bootstrap.  It reads the frozen
5,000-replicate chemical-cluster intervals that the dense and broad benchmarks already
wrote, forms the package's conservative union of the two chemical-cluster schemes
(Murcko/Bemis-Murcko scaffold and Butina), and for every symmetric margin on a
0.010--0.060 grid in steps of 0.005 records whether two one-sided tests at alpha = 0.05
pass.  A symmetric-margin TOST at alpha rejects both one-sided nulls exactly when the
(1 - 2*alpha) interval lies strictly inside the margin, so the 90% interval is the object
that decides the test; the 95% union is carried alongside as the two-sided estimate that
the manuscript reports as its primary result.

Estimand throughout: mean per-ligand pairwise concordance of the scaled two-way-residual
Vina rule minus plain absolute Vina, on within-ligand target pairs.

Nothing here is a confirmatory test.  No margin was preregistered; every margin on the
grid was chosen after the corresponding benchmark had been computed.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

try:  # Support direct CLI execution and package-style imports.
    from . import make_reported_results as reported
except ImportError:  # pragma: no cover - direct CLI execution.
    import make_reported_results as reported  # type: ignore


PACKAGE = Path(__file__).resolve().parents[1]
RESULTS = PACKAGE / "results"
DEFAULT_OUTPUT = RESULTS / "equivalence_margin_sensitivity" / "summary.json"

CONTRAST = "two_way_residual_minus_absolute_vina"

# Grid endpoints in thousandths so the margin values are generated by integer arithmetic
# and are byte-identical across reruns and platforms.
MARGIN_GRID_MILLI = tuple(range(10, 61, 5))

# The margin the Results section used to call prespecified.  It is read from the reporting
# layer rather than restated here, and is retained only so the curve can say explicitly
# whether that one reading survives once it is relabelled post hoc.
RELABELLED_MANUSCRIPT_MARGIN = reported.DENSE_EQUIVALENCE_MARGIN

ALPHA = 0.05
DECISION_RULE = (
    "two one-sided tests at alpha = 0.05: equivalence is declared when the conservative "
    "union of the two chemical-cluster 90% bootstrap intervals lies strictly inside "
    "(-margin, +margin), i.e. when max(|lower|, |upper|) < margin"
)


def margin_values() -> list[float]:
    return [milli / 1000.0 for milli in MARGIN_GRID_MILLI]


def margin_label(milli: int) -> str:
    return f"{milli / 1000.0:.3f}"


def half_width(interval: list[float]) -> float:
    return max(abs(interval[0]), abs(interval[1]))


def margin_curve(interval_90: list[float]) -> tuple[dict[str, bool], float | None]:
    """Decisions on the fixed grid plus the smallest grid margin that passes."""
    reach = half_width(interval_90)
    decisions: dict[str, bool] = {}
    smallest_passing: float | None = None
    for milli in MARGIN_GRID_MILLI:
        margin = milli / 1000.0
        passes = reach < margin
        decisions[margin_label(milli)] = passes
        if passes and smallest_passing is None:
            smallest_passing = margin
    return decisions, smallest_passing


def contrast_block(
    *,
    plugin_mean_difference: float,
    scheme_intervals_90: dict[str, list[float]],
    scheme_intervals_95: dict[str, list[float]],
    scheme_order: tuple[str, ...],
) -> dict[str, Any]:
    union_90 = reported.interval_union(
        {name: {"interval_90": value} for name, value in scheme_intervals_90.items()},
        scheme_order,
        level="interval_90",
    )
    union_95 = reported.interval_union(
        {name: {"interval_95": value} for name, value in scheme_intervals_95.items()},
        scheme_order,
        level="interval_95",
    )
    decisions, smallest_passing = margin_curve(union_90)
    reach = half_width(union_90)
    return {
        "plugin_mean_difference": plugin_mean_difference,
        "cluster_bootstrap_intervals_90": {
            name: scheme_intervals_90[name] for name in scheme_order
        },
        "conservative_union_interval_90": union_90,
        "conservative_union_interval_95": union_95,
        "interval_90_half_width": reach,
        "smallest_supported_symmetric_margin_90_exact": reach,
        "smallest_supported_symmetric_margin_90_rounded_up_3dp": (
            reported.smallest_equivalence_margin(union_90)
        ),
        "smallest_grid_margin_passing": smallest_passing,
        "margin_decisions_90": decisions,
        "relabelled_manuscript_margin_passes": (
            reach < RELABELLED_MANUSCRIPT_MARGIN
        ),
        "excludes_zero_90": union_90[0] > 0.0 or union_90[1] < 0.0,
    }


def davis_block(davis: dict[str, Any]) -> dict[str, Any]:
    stratum = davis["primary"]["paired_comparisons"][CONTRAST]["0.0"]["all_informative"]
    representation = davis["primary"]["representations"]["absolute_vina"]["0.0"][
        "all_informative"
    ]
    schemes = ("murcko_cluster_bootstrap", "butina_cluster_bootstrap")
    uncertainty = stratum["uncertainty"]
    block = contrast_block(
        plugin_mean_difference=stratum["plugin_mean_difference"],
        scheme_intervals_90={
            name: uncertainty[name]["interval_90"] for name in schemes
        },
        scheme_intervals_95={
            name: uncertainty[name]["interval_95"] for name in schemes
        },
        scheme_order=schemes,
    )
    block["benchmark"] = "DAVIS"
    block["source"] = "results/dense_davis_benchmark.json"
    block["estimand_path"] = (
        f"primary.paired_comparisons.{CONTRAST}.0.0.all_informative"
    )
    block["stratum"] = (
        "all informative within-ligand target pairs: exact pKd ties and floor--floor "
        "pairs at the pKd = 5 reporting floor removed"
    )
    block["support"] = {
        "matched_ligands": davis["source_support"]["primary_full_key_ligands"],
        "evaluated_ligands": representation["evaluated_ligands"],
        "targets": davis["source_support"]["shared_targets"],
        "evaluated_within_ligand_target_pairs": representation["evaluated_pairs"],
        "observed_experimental_cells": davis["source_support"][
            "primary_experimental_cells"
        ],
        "murcko_scaffold_clusters": uncertainty["murcko_cluster_bootstrap"][
            "n_clusters"
        ],
        "butina_clusters": uncertainty["butina_cluster_bootstrap"]["n_clusters"],
        "bootstrap_replicates_per_scheme": uncertainty["murcko_cluster_bootstrap"]["n"],
    }
    block["seed"] = davis["analysis_parameters"]["seed"]
    return block


def pkis2_block(pkis2: dict[str, Any]) -> dict[str, Any]:
    stratum = pkis2["primary"]["paired_comparisons"][CONTRAST][
        "absolute_difference_gt_10"
    ]
    representation = pkis2["primary"]["representations"]["absolute_vina"][
        "absolute_difference_gt_10"
    ]
    schemes = ("murcko_cluster_bootstrap", "butina_cluster_bootstrap")
    uncertainty = stratum["uncertainty"]
    block = contrast_block(
        plugin_mean_difference=stratum["plugin_mean_difference"],
        scheme_intervals_90={
            name: uncertainty[name]["interval_90"] for name in schemes
        },
        scheme_intervals_95={
            name: uncertainty[name]["interval_95"] for name in schemes
        },
        scheme_order=schemes,
    )
    block["benchmark"] = "PKIS2"
    block["source"] = "results/dense_pkis2_benchmark.json"
    block["estimand_path"] = (
        f"primary.paired_comparisons.{CONTRAST}.absolute_difference_gt_10"
    )
    block["stratum"] = (
        "within-ligand target pairs whose single-dose percentage-inhibition values "
        "differ by more than 10 percentage points"
    )
    block["support"] = {
        "matched_ligands": pkis2["source_support"]["primary_full_key_ligands"],
        "evaluated_ligands": representation["evaluated_ligands"],
        "targets": pkis2["source_support"]["shared_targets"],
        "evaluated_within_ligand_target_pairs": representation["evaluated_pairs"],
        "observed_experimental_cells": pkis2["source_support"][
            "primary_experimental_cells"
        ],
        "murcko_scaffold_clusters": uncertainty["murcko_cluster_bootstrap"][
            "n_clusters"
        ],
        "butina_clusters": uncertainty["butina_cluster_bootstrap"]["n_clusters"],
        "bootstrap_replicates_per_scheme": uncertainty["murcko_cluster_bootstrap"]["n"],
    }
    block["seed"] = pkis2["analysis_parameters"]["seed"]
    return block


def broad_block(broad: dict[str, Any]) -> dict[str, Any]:
    per_scheme = broad["benchmark"]["paired_comparisons"][CONTRAST]
    headline = broad["headline_contrasts"][CONTRAST]
    schemes = ("scaffold_cluster_bootstrap", "butina_cluster_bootstrap")
    block = contrast_block(
        plugin_mean_difference=per_scheme["plugin_mean_difference"],
        scheme_intervals_90={
            name: per_scheme[name]["interval_90"] for name in schemes
        },
        scheme_intervals_95={
            name: per_scheme[name]["interval_95"] for name in schemes
        },
        scheme_order=schemes,
    )
    block["benchmark"] = "DOCKSTRING-ChEMBL"
    block["source"] = "results/dockstring_chembl_ranking/summary.json"
    block["estimand_path"] = f"headline_contrasts.{CONTRAST}"
    block["stratum"] = (
        "non-tied within-ligand target pairs from exact-relation ChEMBL activities "
        "(median pChEMBL per ligand-target cell, at least two observed targets)"
    )
    representation = broad["benchmark"]["representations"]["absolute_vina"]
    block["support"] = {
        "matched_ligands": broad["support"]["ligands"],
        "evaluated_ligands": representation["evaluated_ligands"],
        "targets": broad["support"]["targets"],
        "evaluated_within_ligand_target_pairs": representation["evaluated_pairs"],
        "observed_experimental_cells": broad["support"][
            "observed_experimental_cells"
        ],
        "murcko_scaffold_clusters": broad["support"]["murcko_scaffold_clusters"],
        "butina_clusters": broad["support"]["butina_clusters"],
        "bootstrap_replicates_per_scheme": broad["bootstrap"]["repeats"],
    }
    block["seed"] = broad["seed"]
    # Consistency check against the interval the broad benchmark itself froze: the union
    # recomputed here must be the union that summary.json already published.
    block["frozen_headline_interval_90"] = headline[
        "conservative_cluster_bootstrap_interval_90"
    ]
    block["matches_frozen_headline_interval_90"] = (
        block["conservative_union_interval_90"]
        == headline["conservative_cluster_bootstrap_interval_90"]
    )
    return block


def secondary_stratum_block(
    *,
    label: str,
    benchmark: str,
    source: str,
    description: str,
    contrast: dict[str, Any],
    representation: dict[str, Any],
    schemes: tuple[str, ...],
) -> dict[str, Any]:
    uncertainty = contrast["uncertainty"]
    block = contrast_block(
        plugin_mean_difference=contrast["plugin_mean_difference"],
        scheme_intervals_90={
            name: uncertainty[name]["interval_90"] for name in schemes
        },
        scheme_intervals_95={
            name: uncertainty[name]["interval_95"] for name in schemes
        },
        scheme_order=schemes,
    )
    block["benchmark"] = benchmark
    block["source"] = source
    block["stratum"] = description
    block["stratum_label"] = label
    block["support"] = {
        "evaluated_ligands": representation["evaluated_ligands"],
        "evaluated_within_ligand_target_pairs": representation["evaluated_pairs"],
    }
    return block


def build(
    davis: dict[str, Any],
    pkis2: dict[str, Any],
    broad: dict[str, Any],
) -> dict[str, Any]:
    benchmarks = {
        "DAVIS": davis_block(davis),
        "PKIS2": pkis2_block(pkis2),
        "DOCKSTRING-ChEMBL": broad_block(broad),
    }

    dense_schemes = ("murcko_cluster_bootstrap", "butina_cluster_bootstrap")
    secondary = {
        "DAVIS_both_uncensored": secondary_stratum_block(
            label="both_uncensored",
            benchmark="DAVIS",
            source="results/dense_davis_benchmark.json",
            description=(
                "exploratory outcome-conditioned stratum: both DAVIS measurements above "
                "the pKd = 5 reporting floor"
            ),
            contrast=davis["primary"]["paired_comparisons"][CONTRAST]["0.0"][
                "both_uncensored"
            ],
            representation=davis["primary"]["representations"]["absolute_vina"]["0.0"][
                "both_uncensored"
            ],
            schemes=dense_schemes,
        ),
        "DAVIS_floor_vs_uncensored": secondary_stratum_block(
            label="floor_vs_uncensored",
            benchmark="DAVIS",
            source="results/dense_davis_benchmark.json",
            description=(
                "exploratory outcome-conditioned stratum: one measurement at the pKd = 5 "
                "floor and one above it"
            ),
            contrast=davis["primary"]["paired_comparisons"][CONTRAST]["0.0"][
                "floor_vs_uncensored"
            ],
            representation=davis["primary"]["representations"]["absolute_vina"]["0.0"][
                "floor_vs_uncensored"
            ],
            schemes=dense_schemes,
        ),
        "PKIS2_both_active": secondary_stratum_block(
            label="both_active",
            benchmark="PKIS2",
            source="results/dense_pkis2_benchmark.json",
            description=(
                "exploratory outcome-conditioned stratum: both PKIS2 values at least 65% "
                "inhibition and the primary >10 percentage-point margin retained"
            ),
            contrast=pkis2["primary"]["exploratory_both_active_paired_comparisons"][
                CONTRAST
            ],
            representation=pkis2["primary"][
                "exploratory_both_active_pairwise_concordance"
            ]["absolute_vina"],
            schemes=dense_schemes,
        ),
    }

    primary_order = ("DAVIS", "PKIS2", "DOCKSTRING-ChEMBL")
    smallest_common = max(
        benchmarks[name]["interval_90_half_width"] for name in primary_order
    )
    common_grid_margin = None
    for milli in MARGIN_GRID_MILLI:
        if smallest_common < milli / 1000.0:
            common_grid_margin = milli / 1000.0
            break

    return {
        "analysis_question": (
            "Across which symmetric equivalence margins does a two-one-sided-test "
            "reading of the scaled-two-way-residual-minus-absolute-Vina ranking contrast "
            "pass, on the dense DAVIS and PKIS2 benchmarks and on the broad "
            "DOCKSTRING-ChEMBL benchmark?"
        ),
        "status": "post_hoc_equivalence_margin_sensitivity_complete",
        "estimand": (
            "mean per-ligand pairwise concordance of the scaled two-way-residual Vina "
            "rule minus plain absolute Vina, on within-ligand target pairs"
        ),
        "prespecification": (
            "post hoc throughout: no equivalence margin was preregistered, and every "
            "margin on this grid was chosen after the corresponding benchmark had been "
            "computed. The Results sentence that called +/-0.03 prespecified is "
            "withdrawn; this curve replaces it."
        ),
        "decision_rule": {
            "test": "two one-sided tests (TOST)",
            "alpha": ALPHA,
            "interval_used": "conservative union of the two chemical-cluster 90% bootstrap intervals",
            "criterion": DECISION_RULE,
            "strictness": (
                "strict inequality; a margin exactly equal to the interval half-width "
                "does not pass"
            ),
            "interval_union_rule": (
                "elementwise min of lower bounds and max of upper bounds across the two "
                "chemical-cluster schemes, the package-wide conservative union"
            ),
        },
        "margin_grid": {
            "start": 0.010,
            "stop": 0.060,
            "step": 0.005,
            "values": margin_values(),
            "labels": [margin_label(milli) for milli in MARGIN_GRID_MILLI],
        },
        "bootstrap_contract": {
            "replicates_per_scheme": 5000,
            "chemical_cluster_schemes_dense": list(dense_schemes),
            "chemical_cluster_schemes_broad": [
                "scaffold_cluster_bootstrap",
                "butina_cluster_bootstrap",
            ],
            "note": (
                "no bootstrap is re-run here; the intervals are read from the frozen "
                "benchmark artifacts, which used 5,000 replicates per scheme"
            ),
        },
        "seeds": {
            "dense_davis_benchmark": davis["analysis_parameters"]["seed"],
            "dense_pkis2_benchmark": pkis2["analysis_parameters"]["seed"],
            "dockstring_chembl_ranking": broad["seed"],
            "this_script": (
                "none; the script is a deterministic read-and-tabulate over frozen "
                "intervals and draws no random numbers"
            ),
        },
        "support": {
            name: benchmarks[name]["support"] for name in primary_order
        },
        "benchmarks": benchmarks,
        "cross_benchmark_summary": {
            "primary_benchmark_order": list(primary_order),
            "smallest_supported_symmetric_margin_90_exact": {
                name: benchmarks[name]["smallest_supported_symmetric_margin_90_exact"]
                for name in primary_order
            },
            "smallest_grid_margin_passing": {
                name: benchmarks[name]["smallest_grid_margin_passing"]
                for name in primary_order
            },
            "largest_half_width_across_primary_benchmarks": smallest_common,
            "smallest_grid_margin_passing_on_all_three": common_grid_margin,
            "relabelled_manuscript_margin": RELABELLED_MANUSCRIPT_MARGIN,
            "relabelled_manuscript_margin_passes_everywhere": all(
                benchmarks[name]["relabelled_manuscript_margin_passes"]
                for name in primary_order
            ),
            "any_primary_benchmark_excludes_zero_at_90": any(
                benchmarks[name]["excludes_zero_90"] for name in primary_order
            ),
        },
        "secondary_outcome_conditioned_strata": secondary,
        "claim_boundary": (
            "This is a post hoc equivalence reading of already-computed intervals, not a "
            "confirmatory or preregistered test, and it re-runs no resampling. Passing a "
            "margin bounds the size of any residual-rule advantage on the evaluated "
            "ligand-target pairs of these three benchmarks; it does not show the two "
            "rules are identical, does not extend to other chemical supports, target "
            "panels, scoring functions or endpoints, and does not license the word "
            "'prespecified' anywhere. The conservative union widens the interval and "
            "therefore makes every decision here harder, not easier. The equivalence "
            "holds on the primary strata only: the exploratory binder-only strata "
            "(DAVIS both_uncensored, PKIS2 both_active) show intervals excluding zero in "
            "favour of the residual rule and fail every margin on this grid, so no "
            "global 'the rules are equivalent' statement is supported."
        ),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--dense-davis",
        type=Path,
        default=RESULTS / "dense_davis_benchmark.json",
    )
    parser.add_argument(
        "--dense-pkis2",
        type=Path,
        default=RESULTS / "dense_pkis2_benchmark.json",
    )
    parser.add_argument(
        "--broad-ranking",
        type=Path,
        default=RESULTS / "dockstring_chembl_ranking" / "summary.json",
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    result = build(
        json.loads(args.dense_davis.read_text()),
        json.loads(args.dense_pkis2.read_text()),
        json.loads(args.broad_ranking.read_text()),
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
