#!/usr/bin/env python3
"""Boundary audit for residual docking geometry and ChEMBL target retrieval.

The audit answers a deliberately narrow operational question: does the larger
spectral dimension exposed by two-way centering improve recovery of known active
targets?  It reconstructs the strict ChEMBL active-pair benchmark entirely from
frozen package inputs and compares three score representations:

* ``absolute``: clipped and column-mean-imputed Vina scores;
* ``column_z``: target-wise z scores across the full Docking-44 support; and
* ``two_way_residual``: the two-way ANOVA residual in raw score units.

Subtracting a row constant cannot change within-ligand target order.  Therefore
``column_z`` and ``two_way_residual`` need NOT have identical rankings; this is an
explicit tested identity, not an empirical approximation.

Inference has two levels.  Paired uncertainty is estimated by resampling whole
compounds and frozen Butina clusters.  Null performance is estimated both by a
legacy target-frequency-multiset permutation and by a stricter bipartite switch
chain that preserves every compound's active-target count, every target's
frequency, and binary compound-target incidence.

No row-level compound, structure, target, or activity identifiers are written to
the output directory.  Only aggregate CSV/JSON records and an autogenerated
README are emitted.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Iterable

import numpy as np
import pandas as pd
from rdkit import Chem, RDLogger
from scipy import stats


RDLogger.DisableLog("rdApp.*")

PACKAGE = Path(__file__).resolve().parents[1]
FROZEN = PACKAGE / "data" / "frozen"
DEFAULT_SCORES = FROZEN / "df_final_v4.csv.gz"
DEFAULT_ACTIVITIES = (
    FROZEN / "negative_results_paper" / "analysis" / "chembl_activities_full.csv.gz"
)
DEFAULT_OUTPUT = PACKAGE / "results" / "residual_mie_boundary_audit"

DOCK44 = [
    "1m2z", "1pbq", "1xoq", "2rh1", "2vt4", "2ydo", "2z5x", "3b66",
    "3kk6", "3ln1", "3rze", "4djh", "4ey7", "4iar", "4mqs", "4n6h",
    "5cxv", "5i71", "5tvn", "5u09", "5va1", "6cm4", "6kpf", "6kux",
    "6lqa", "6pdj", "6x3x", "6y1z", "7f8y", "7kwe", "7ljd", "7wc9",
    "7xnk", "7ym8", "8e9y", "8ef6", "8fhs", "8pjk", "8st0", "8wty",
    "8xvk", "8yn3", "9eo4", "V1A",
]

REPRESENTATIONS = ("absolute", "column_z", "two_way_residual")
WEIGHTINGS = ("pair_weighted", "compound_balanced")
METRICS = ("mean_rank_percentile", "top1", "top3", "top5")
LOWER_IS_BETTER = {"mean_rank_percentile"}


@dataclass(frozen=True)
class AuditConfig:
    pchembl_threshold: float = 6.0
    bootstrap_replicates: int = 5_000
    null_replicates: int = 5_000
    switch_burnin_per_edge: int = 20
    switch_between_per_edge: int = 2
    seed: int = 202_608_03


def sha256_file(path: Path) -> str:
    """Return a lowercase SHA-256 digest for a local file."""

    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _json_safe(value: Any) -> Any:
    """Convert numpy/pandas scalars and non-finite floats for strict JSON."""

    if isinstance(value, dict):
        return {str(key): _json_safe(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_json_safe(item) for item in value]
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (np.floating, float)):
        number = float(value)
        return number if np.isfinite(number) else None
    if isinstance(value, (np.bool_,)):
        return bool(value)
    return value


def inchi_key(smiles: str) -> str | None:
    """Canonical InChIKey used only for the frozen input join."""

    molecule = Chem.MolFromSmiles(str(smiles))
    if molecule is None:
        return None
    return Chem.MolToInchiKey(molecule)


def derive_strict_active_pairs(
    score_frame: pd.DataFrame,
    activities_path: Path,
    pchembl_threshold: float,
) -> pd.DataFrame:
    """Reconstruct strict active compound-target pairs from frozen inputs.

    The returned frame is internal only and is never persisted.  It contains one
    row per unique Docking-44 compound-target pair whose exact-relation median
    pChEMBL is >= ``pchembl_threshold``. Only Ki, Kd, IC50, and EC50 records enter
    the median.
    """

    required_score = {"ligand_id", "Cleaned SMILES"}
    missing_score = required_score.difference(score_frame.columns)
    if missing_score:
        raise ValueError(f"score input lacks required columns: {sorted(missing_score)}")

    activities = pd.read_csv(activities_path)
    required_activities = {
        "canonical_smiles",
        "panel_key",
        "pchembl_value",
        "standard_relation",
        "standard_type",
    }
    missing_activities = required_activities.difference(activities.columns)
    if missing_activities:
        raise ValueError(
            "activity input lacks required columns: "
            f"{sorted(missing_activities)}"
        )

    mapping = score_frame[["ligand_id", "Cleaned SMILES"]].copy()
    if mapping["ligand_id"].duplicated().any():
        raise ValueError("score input contains duplicate ligand_id values")
    mapping["inchikey"] = mapping["Cleaned SMILES"].map(inchi_key)
    if mapping["inchikey"].isna().any():
        count = int(mapping["inchikey"].isna().sum())
        raise ValueError(f"failed to parse {count} frozen cleaned SMILES")
    if mapping["inchikey"].duplicated().any():
        raise ValueError("frozen score input contains duplicate canonical InChIKeys")

    endpoint_types = {"Ki", "Kd", "IC50", "EC50"}
    activities["pchembl_numeric"] = pd.to_numeric(
        activities["pchembl_value"], errors="coerce"
    )
    eligible = activities.loc[
        activities["standard_relation"].astype(str).eq("=")
        & activities["standard_type"].isin(endpoint_types)
        & activities["panel_key"].isin(DOCK44)
        & activities["canonical_smiles"].notna()
        & activities["pchembl_numeric"].notna(),
        ["canonical_smiles", "panel_key", "pchembl_numeric"],
    ].copy()
    if eligible.empty:
        raise ValueError("no ChEMBL records satisfy the strict activity contract")
    unique_smiles = eligible["canonical_smiles"].drop_duplicates()
    smiles_to_key = {smiles: inchi_key(smiles) for smiles in unique_smiles}
    eligible["inchikey"] = eligible["canonical_smiles"].map(smiles_to_key)
    eligible = eligible.dropna(subset=["inchikey"])
    medians = (
        eligible.groupby(["inchikey", "panel_key"], as_index=False)[
            "pchembl_numeric"
        ]
        .median()
        .rename(columns={"panel_key": "pdb"})
    )
    active = medians.loc[
        medians["pchembl_numeric"] >= pchembl_threshold,
        ["inchikey", "pdb"],
    ].drop_duplicates()
    joined = mapping[["ligand_id", "inchikey"]].merge(
        active,
        on="inchikey",
        how="inner",
        validate="one_to_many",
    )
    pairs = joined[["ligand_id", "pdb"]].drop_duplicates().copy()
    pairs = pairs.sort_values(["ligand_id", "pdb"], kind="mergesort").reset_index(
        drop=True
    )
    if pairs.empty:
        raise ValueError("strict active-pair reconstruction produced no overlap")
    return pairs


def preprocess_score_representations(
    score_frame: pd.DataFrame,
) -> tuple[dict[str, np.ndarray], dict[str, int]]:
    """Build the three prespecified score representations.

    This mirrors the legacy benchmark preprocessing: numeric coercion, clipping
    positive Vina scores to zero, target-mean imputation, then target-wise sample
    standardization (ddof=1).  The two-way residual is the manuscript's definition,
    the additive two-way ANOVA residual in raw score units, so within one ligand it
    preserves the ordering of column-centred scores rather than of column-z scores.
    Bundles frozen before 2026-08-12 row-centred the column-z matrix instead.
    """

    missing = set(DOCK44).difference(score_frame.columns)
    if missing:
        raise ValueError(f"score input lacks Docking-44 columns: {sorted(missing)}")
    numeric = score_frame[DOCK44].apply(pd.to_numeric, errors="coerce")
    missing_before = int(numeric.isna().sum().sum())
    positive_before = int((numeric > 0).sum().sum())
    clipped = numeric.clip(upper=0.0)
    means = clipped.mean(axis=0)
    if means.isna().any():
        raise ValueError("at least one target column has no finite score")
    absolute = clipped.fillna(means).to_numpy(dtype=float)
    if not np.isfinite(absolute).all():
        raise ValueError("non-finite values remain after score preprocessing")

    column_means = absolute.mean(axis=0)
    column_sds = absolute.std(axis=0, ddof=1)
    if np.any(column_sds <= 0):
        raise ValueError("at least one target column has zero score variance")
    column_z = (absolute - column_means) / column_sds
    column_centred = absolute - column_means
    two_way_residual = column_centred - column_centred.mean(axis=1, keepdims=True)
    return (
        {
            "absolute": absolute,
            "column_z": column_z,
            "two_way_residual": two_way_residual,
        },
        {
            "missing_cells_before_imputation": missing_before,
            "positive_cells_clipped_to_zero": positive_before,
        },
    )


def average_rank_matrix(scores: np.ndarray) -> np.ndarray:
    """Return tie-aware 1-based within-row ranks; lower scores are better."""

    scores = np.asarray(scores, dtype=float)
    if scores.ndim != 2:
        raise ValueError("scores must be a two-dimensional matrix")
    if not np.isfinite(scores).all():
        raise ValueError("scores must be finite before ranking")
    return stats.rankdata(scores, axis=1, method="average")


def rank_score_representations(
    representations: dict[str, np.ndarray],
    selected_rows: np.ndarray,
) -> tuple[dict[str, np.ndarray], dict[str, float | bool]]:
    """Rank each representation, and record the row-shift identity that does hold.

    Under the manuscript's definition the two-way residual is the column-centred
    matrix minus each ligand's mean, so within a ligand it preserves the ordering
    of **column-centred** scores, not of column-z scores. Those two orderings
    differ whenever target columns have unequal spread, so each representation is
    ranked independently and the identity that survives is checked explicitly.
    """

    absolute = representations["absolute"][selected_rows]
    column_z = representations["column_z"][selected_rows]
    residual = representations["two_way_residual"][selected_rows]

    column_centred = absolute - representations["absolute"].mean(axis=0)
    reconstructed = column_centred - column_centred.mean(axis=1, keepdims=True)
    maximum_reconstruction_error = float(np.max(np.abs(residual - reconstructed)))
    if maximum_reconstruction_error > 1e-12:
        raise AssertionError("two-way residual does not equal row-centred column-centred scores")

    ranks = {
        "absolute": average_rank_matrix(absolute),
        "column_z": average_rank_matrix(column_z),
        "two_way_residual": average_rank_matrix(residual),
    }
    maximum_rank_difference = float(
        np.max(np.abs(ranks["column_z"] - ranks["two_way_residual"]))
    )
    return ranks, {
        "maximum_absolute_score_reconstruction_error": maximum_reconstruction_error,
        "maximum_absolute_rank_difference": maximum_rank_difference,
        "all_rankings_identical": bool(maximum_rank_difference == 0.0),
    }


def active_incidence(
    score_frame: pd.DataFrame,
    pairs: pd.DataFrame,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Return selected score rows, binary incidence, cluster labels, and degrees."""

    ligand_order = score_frame["ligand_id"].tolist()
    ligand_to_score_row = {value: index for index, value in enumerate(ligand_order)}
    target_to_index = {value: index for index, value in enumerate(DOCK44)}

    pair_compounds = set(pairs["ligand_id"])
    compound_values = [value for value in ligand_order if value in pair_compounds]
    compound_to_local = {value: index for index, value in enumerate(compound_values)}
    incidence = np.zeros((len(compound_values), len(DOCK44)), dtype=bool)
    for row in pairs.itertuples(index=False):
        incidence[compound_to_local[row.ligand_id], target_to_index[row.pdb]] = True
    degrees = incidence.sum(axis=1)
    if np.any(degrees == 0):
        raise AssertionError("selected compounds must have at least one active target")

    selected_rows = np.array(
        [ligand_to_score_row[value] for value in compound_values], dtype=int
    )
    cluster_by_ligand = score_frame.set_index("ligand_id")["Butina_clusters"]
    selected_clusters = cluster_by_ligand.loc[compound_values]
    if selected_clusters.isna().any():
        raise ValueError("missing frozen Butina cluster labels in benchmark compounds")
    cluster_labels = selected_clusters.astype(str).to_numpy()
    return selected_rows, incidence, cluster_labels, degrees


def metric_value_matrices(rank_matrix: np.ndarray) -> dict[str, np.ndarray]:
    """Convert ranks to prespecified per-compound/per-target metric values."""

    panel_size = rank_matrix.shape[1]
    return {
        "mean_rank_percentile": (rank_matrix - 1.0) / (panel_size - 1.0),
        "top1": (rank_matrix <= 1.0).astype(float),
        "top3": (rank_matrix <= 3.0).astype(float),
        "top5": (rank_matrix <= 5.0).astype(float),
    }


def aggregate_metric(
    values: np.ndarray,
    incidence: np.ndarray,
    weighting: str,
) -> float:
    """Aggregate a metric with pair or compound-balanced weighting."""

    degrees = incidence.sum(axis=1)
    if np.any(degrees <= 0):
        raise ValueError("every compound must have at least one active target")
    if weighting == "pair_weighted":
        return float(values[incidence].mean())
    if weighting == "compound_balanced":
        per_compound = (values * incidence).sum(axis=1) / degrees
        return float(per_compound.mean())
    raise ValueError(f"unknown weighting: {weighting}")


def contribution_arrays(
    values: np.ndarray,
    incidence: np.ndarray,
) -> dict[str, np.ndarray]:
    """Sufficient per-compound arrays for paired hierarchical bootstraps."""

    pair_count = incidence.sum(axis=1).astype(float)
    pair_sum = (values * incidence).sum(axis=1)
    return {
        "pair_sum": pair_sum,
        "pair_count": pair_count,
        "compound_sum": pair_sum / pair_count,
        "compound_count": np.ones(len(pair_count), dtype=float),
    }


def grouped_sufficient_statistics(
    contributions: dict[str, np.ndarray],
    groups: np.ndarray,
) -> dict[str, np.ndarray]:
    """Collapse per-compound sufficient statistics to bootstrap groups."""

    _, inverse = np.unique(np.asarray(groups, dtype=str), return_inverse=True)
    n_groups = int(inverse.max()) + 1
    grouped: dict[str, np.ndarray] = {}
    for key, values in contributions.items():
        grouped[key] = np.bincount(inverse, weights=values, minlength=n_groups)
    return grouped


def bootstrap_draw_indices(
    n_units: int,
    replicates: int,
    rng: np.random.Generator,
) -> np.ndarray:
    """Generate a shared bootstrap index matrix for paired comparisons."""

    if n_units < 2:
        raise ValueError("at least two bootstrap units are required")
    return rng.integers(0, n_units, size=(replicates, n_units))


def bootstrap_distribution(
    sufficient: dict[str, np.ndarray],
    draw_indices: np.ndarray,
    weighting: str,
) -> np.ndarray:
    """Evaluate one metric over a matrix of bootstrap draws."""

    if weighting == "pair_weighted":
        numerator = sufficient["pair_sum"][draw_indices].sum(axis=1)
        denominator = sufficient["pair_count"][draw_indices].sum(axis=1)
    elif weighting == "compound_balanced":
        numerator = sufficient["compound_sum"][draw_indices].sum(axis=1)
        denominator = sufficient["compound_count"][draw_indices].sum(axis=1)
    else:
        raise ValueError(f"unknown weighting: {weighting}")
    return numerator / denominator


def percentile_interval(values: np.ndarray) -> tuple[float, float]:
    """Return a percentile 95% interval."""

    low, high = np.percentile(np.asarray(values, dtype=float), [2.5, 97.5])
    return float(low), float(high)


def edge_arrays(incidence: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Return compound and target indices for each active binary edge."""

    return tuple(np.asarray(item, dtype=int) for item in np.where(incidence))  # type: ignore[return-value]


def switch_edges_in_place(
    incidence: np.ndarray,
    edge_compounds: np.ndarray,
    edge_targets: np.ndarray,
    accepted_swaps: int,
    rng: np.random.Generator,
) -> int:
    """Perform degree-preserving double-edge swaps on a binary incidence graph.

    Compound indices attached to edge slots remain fixed; swapping two target
    endpoints preserves row and column sums.  Cross edges are required to be
    absent, preventing duplicate compound-target pairs.
    """

    edge_count = len(edge_targets)
    accepted = 0
    attempts = 0
    maximum_attempts = max(1000, accepted_swaps * 100)
    while accepted < accepted_swaps:
        attempts += 1
        if attempts > maximum_attempts:
            raise RuntimeError(
                "bipartite switch chain could not reach requested accepted swaps"
            )
        first, second = rng.integers(0, edge_count, size=2)
        if first == second:
            continue
        compound_first = edge_compounds[first]
        compound_second = edge_compounds[second]
        target_first = edge_targets[first]
        target_second = edge_targets[second]
        if compound_first == compound_second or target_first == target_second:
            continue
        if incidence[compound_first, target_second]:
            continue
        if incidence[compound_second, target_first]:
            continue

        incidence[compound_first, target_first] = False
        incidence[compound_second, target_second] = False
        incidence[compound_first, target_second] = True
        incidence[compound_second, target_first] = True
        edge_targets[first], edge_targets[second] = target_second, target_first
        accepted += 1
    return attempts


def edge_label_metric(
    values: np.ndarray,
    edge_compounds: np.ndarray,
    edge_targets: np.ndarray,
    compound_degrees: np.ndarray,
    weighting: str,
) -> float:
    """Aggregate values for a target-label permutation, including duplicates."""

    selected = values[edge_compounds, edge_targets]
    if weighting == "pair_weighted":
        return float(selected.mean())
    if weighting == "compound_balanced":
        sums = np.bincount(
            edge_compounds, weights=selected, minlength=len(compound_degrees)
        )
        return float(np.mean(sums / compound_degrees))
    raise ValueError(f"unknown weighting: {weighting}")


def empirical_tail_p(
    null_values: np.ndarray,
    observed: float,
    lower_is_better: bool,
) -> float:
    """Plus-one corrected one-sided empirical probability."""

    null_values = np.asarray(null_values, dtype=float)
    if lower_is_better:
        extreme = int(np.sum(null_values <= observed))
    else:
        extreme = int(np.sum(null_values >= observed))
    return float((extreme + 1) / (len(null_values) + 1))


def run_null_models(
    value_matrices: dict[str, dict[str, np.ndarray]],
    incidence: np.ndarray,
    config: AuditConfig,
) -> tuple[pd.DataFrame, dict[str, Any]]:
    """Run target-frequency and fixed-margin null models."""

    rng = np.random.default_rng(config.seed + 101)
    edge_compounds, original_targets = edge_arrays(incidence)
    degrees = incidence.sum(axis=1).astype(float)
    target_degrees = incidence.sum(axis=0).copy()
    n_edges = len(original_targets)

    distributions: dict[tuple[str, str, str, str], np.ndarray] = {}
    for model in ("target_frequency_multiset", "fixed_margin_bipartite_switch"):
        for representation in REPRESENTATIONS:
            for weighting in WEIGHTINGS:
                for metric in METRICS:
                    distributions[(model, representation, weighting, metric)] = np.empty(
                        config.null_replicates, dtype=float
                    )

    # Legacy frequency-matched label permutation.  It preserves the exact target
    # multiset but can create repeated target labels within a compound.
    for replicate in range(config.null_replicates):
        shuffled_targets = rng.permutation(original_targets)
        for representation in REPRESENTATIONS:
            for metric in METRICS:
                values = value_matrices[representation][metric]
                for weighting in WEIGHTINGS:
                    distributions[
                        (
                            "target_frequency_multiset",
                            representation,
                            weighting,
                            metric,
                        )
                    ][replicate] = edge_label_metric(
                        values,
                        edge_compounds,
                        shuffled_targets,
                        degrees,
                        weighting,
                    )

    # Stricter binary fixed-margin null.  The Markov chain preserves both margin
    # vectors and cannot create duplicate compound-target edges.
    switched_incidence = incidence.copy()
    switched_compounds, switched_targets = edge_arrays(switched_incidence)
    burnin_swaps = config.switch_burnin_per_edge * n_edges
    burnin_attempts = switch_edges_in_place(
        switched_incidence,
        switched_compounds,
        switched_targets,
        burnin_swaps,
        rng,
    )
    between_swaps = config.switch_between_per_edge * n_edges
    total_between_attempts = 0
    for replicate in range(config.null_replicates):
        total_between_attempts += switch_edges_in_place(
            switched_incidence,
            switched_compounds,
            switched_targets,
            between_swaps,
            rng,
        )
        for representation in REPRESENTATIONS:
            for metric in METRICS:
                values = value_matrices[representation][metric]
                for weighting in WEIGHTINGS:
                    distributions[
                        (
                            "fixed_margin_bipartite_switch",
                            representation,
                            weighting,
                            metric,
                        )
                    ][replicate] = aggregate_metric(
                        values, switched_incidence, weighting
                    )

    if not np.array_equal(switched_incidence.sum(axis=1), incidence.sum(axis=1)):
        raise AssertionError("fixed-margin null changed compound degrees")
    if not np.array_equal(switched_incidence.sum(axis=0), target_degrees):
        raise AssertionError("fixed-margin null changed target frequencies")

    rows: list[dict[str, Any]] = []
    for key, values in distributions.items():
        null_model, representation, weighting, metric = key
        observed = aggregate_metric(
            value_matrices[representation][metric], incidence, weighting
        )
        null_mean = float(values.mean())
        null_sd = float(values.std(ddof=1))
        favorable_excess = (
            null_mean - observed
            if metric in LOWER_IS_BETTER
            else observed - null_mean
        )
        low, high = percentile_interval(values)
        rows.append(
            {
                "null_model": null_model,
                "representation": representation,
                "weighting": weighting,
                "metric": metric,
                "observed": observed,
                "null_mean": null_mean,
                "null_standard_deviation": null_sd,
                "null_ci95_low": low,
                "null_ci95_high": high,
                "favorable_excess_over_null_mean": favorable_excess,
                "favorable_standardized_excess": favorable_excess / null_sd,
                "one_sided_empirical_p": empirical_tail_p(
                    values, observed, metric in LOWER_IS_BETTER
                ),
                "favorable_direction": (
                    "lower" if metric in LOWER_IS_BETTER else "higher"
                ),
            }
        )
    diagnostics = {
        "null_replicates": config.null_replicates,
        "number_of_binary_edges": n_edges,
        "switch_chain_burnin_accepted_swaps": burnin_swaps,
        "switch_chain_burnin_attempts": burnin_attempts,
        "switch_chain_between_samples_accepted_swaps": between_swaps,
        "switch_chain_total_between_sample_attempts": total_between_attempts,
        "row_degrees_preserved": True,
        "target_frequencies_preserved": True,
        "binary_incidence_preserved": True,
    }
    return pd.DataFrame(rows), diagnostics


def run_bootstraps(
    value_matrices: dict[str, dict[str, np.ndarray]],
    incidence: np.ndarray,
    cluster_labels: np.ndarray,
    config: AuditConfig,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Run shared compound and Butina-cluster paired bootstraps."""

    rng = np.random.default_rng(config.seed + 211)
    n_compounds = incidence.shape[0]
    n_clusters = len(np.unique(cluster_labels))
    compound_draws = bootstrap_draw_indices(
        n_compounds, config.bootstrap_replicates, rng
    )
    cluster_draws = bootstrap_draw_indices(
        n_clusters, config.bootstrap_replicates, rng
    )

    observed_rows: list[dict[str, Any]] = []
    distributions: dict[tuple[str, str, str, str], np.ndarray] = {}
    for representation in REPRESENTATIONS:
        for metric in METRICS:
            contributions = contribution_arrays(
                value_matrices[representation][metric], incidence
            )
            grouped = grouped_sufficient_statistics(contributions, cluster_labels)
            for weighting in WEIGHTINGS:
                compound_distribution = bootstrap_distribution(
                    contributions, compound_draws, weighting
                )
                cluster_distribution = bootstrap_distribution(
                    grouped, cluster_draws, weighting
                )
                distributions[
                    (representation, weighting, metric, "compound")
                ] = compound_distribution
                distributions[
                    (representation, weighting, metric, "butina_cluster")
                ] = cluster_distribution
                compound_low, compound_high = percentile_interval(
                    compound_distribution
                )
                cluster_low, cluster_high = percentile_interval(cluster_distribution)
                observed_rows.append(
                    {
                        "representation": representation,
                        "weighting": weighting,
                        "metric": metric,
                        "estimate": aggregate_metric(
                            value_matrices[representation][metric],
                            incidence,
                            weighting,
                        ),
                        "compound_bootstrap_ci95_low": compound_low,
                        "compound_bootstrap_ci95_high": compound_high,
                        "butina_cluster_bootstrap_ci95_low": cluster_low,
                        "butina_cluster_bootstrap_ci95_high": cluster_high,
                        "bootstrap_replicates": config.bootstrap_replicates,
                    }
                )

    contrast_rows: list[dict[str, Any]] = []
    comparisons = (
        ("column_z", "absolute"),
        ("two_way_residual", "absolute"),
        ("two_way_residual", "column_z"),
    )
    for comparator, reference in comparisons:
        for weighting in WEIGHTINGS:
            for metric in METRICS:
                record: dict[str, Any] = {
                    "comparator": comparator,
                    "reference": reference,
                    "contrast": f"{comparator}_minus_{reference}",
                    "weighting": weighting,
                    "metric": metric,
                    "estimate": (
                        aggregate_metric(
                            value_matrices[comparator][metric], incidence, weighting
                        )
                        - aggregate_metric(
                            value_matrices[reference][metric], incidence, weighting
                        )
                    ),
                    "favorable_contrast_direction": (
                        "negative" if metric in LOWER_IS_BETTER else "positive"
                    ),
                }
                for unit in ("compound", "butina_cluster"):
                    difference = (
                        distributions[(comparator, weighting, metric, unit)]
                        - distributions[(reference, weighting, metric, unit)]
                    )
                    low, high = percentile_interval(difference)
                    record[f"{unit}_bootstrap_ci95_low"] = low
                    record[f"{unit}_bootstrap_ci95_high"] = high
                contrast_rows.append(record)
    return pd.DataFrame(observed_rows), pd.DataFrame(contrast_rows)


def compact_distribution_summary(values: Iterable[float]) -> dict[str, float]:
    """Five-number-like aggregate without disclosing row-level identifiers."""

    array = np.asarray(list(values), dtype=float)
    return {
        "minimum": float(array.min()),
        "quartile_1": float(np.percentile(array, 25)),
        "median": float(np.median(array)),
        "quartile_3": float(np.percentile(array, 75)),
        "maximum": float(array.max()),
    }


def write_readme(
    output_dir: Path,
    summary: dict[str, Any],
    observed_metrics: pd.DataFrame,
    contrasts: pd.DataFrame,
    null_summary: pd.DataFrame,
) -> None:
    """Write a concise, value-aware README for the aggregate output package."""

    def metric(rep: str, name: str, weighting: str = "compound_balanced") -> float:
        row = observed_metrics[
            (observed_metrics["representation"] == rep)
            & (observed_metrics["metric"] == name)
            & (observed_metrics["weighting"] == weighting)
        ].iloc[0]
        return float(row["estimate"])

    def contrast(name: str, metric_name: str) -> pd.Series:
        return contrasts[
            (contrasts["contrast"] == name)
            & (contrasts["metric"] == metric_name)
            & (contrasts["weighting"] == "compound_balanced")
        ].iloc[0]

    def null_p(rep: str, name: str) -> float:
        row = null_summary[
            (null_summary["null_model"] == "fixed_margin_bipartite_switch")
            & (null_summary["representation"] == rep)
            & (null_summary["metric"] == name)
            & (null_summary["weighting"] == "compound_balanced")
        ].iloc[0]
        return float(row["one_sided_empirical_p"])

    def null_record(rep: str, name: str) -> pd.Series:
        return null_summary[
            (null_summary["null_model"] == "fixed_margin_bipartite_switch")
            & (null_summary["representation"] == rep)
            & (null_summary["metric"] == name)
            & (null_summary["weighting"] == "compound_balanced")
        ].iloc[0]

    rank_delta = contrast("column_z_minus_absolute", "mean_rank_percentile")
    top5_delta = contrast("column_z_minus_absolute", "top5")
    residual_top5_null = null_record("two_way_residual", "top5")
    counts = summary["benchmark_counts"]
    text = f"""# Residual/MIE boundary audit

This directory contains aggregate results from a frozen ChEMBL active-target
benchmark on Docking-44. The active set uses exact-relation Ki/Kd/IC50/EC50
records, median aggregation per compound-target cell, and pChEMBL >=
{summary['config']['pchembl_threshold']:.1f}. It contains
{counts['active_pairs']} compound-target pairs, {counts['compounds']} compounds,
and {counts['represented_targets']} represented targets within the 44-target
ranking panel. No row-level compound, structure, target, or activity identifiers
are emitted here.

## Prespecified comparison

Lower mean rank percentile and higher top-k rates are favorable. With equal
weight per compound, absolute Vina gives mean rank percentile
{metric('absolute', 'mean_rank_percentile'):.4f} and top-5 rate
{metric('absolute', 'top5'):.4f}; column-z gives
{metric('column_z', 'mean_rank_percentile'):.4f} and
{metric('column_z', 'top5'):.4f}. The column-z minus absolute paired difference
is {float(rank_delta['estimate']):+.4f} for rank percentile (Butina-cluster 95%
CI {float(rank_delta['butina_cluster_bootstrap_ci95_low']):+.4f} to
{float(rank_delta['butina_cluster_bootstrap_ci95_high']):+.4f}) and
{float(top5_delta['estimate']):+.4f} for top-5 rate (cluster 95% CI
{float(top5_delta['butina_cluster_bootstrap_ci95_low']):+.4f} to
{float(top5_delta['butina_cluster_bootstrap_ci95_high']):+.4f}).

Against the fixed-margin target-frequency null, the one-sided compound-balanced
mean-rank probabilities are {null_p('absolute', 'mean_rank_percentile'):.4g} for
absolute Vina and {null_p('column_z', 'mean_rank_percentile'):.4g} for column-z.
The residual top-5 rate remains above its matched null
({float(residual_top5_null['observed']):.4f} versus
{float(residual_top5_null['null_mean']):.4f}; one-sided
p={float(residual_top5_null['one_sided_empirical_p']):.4g}). Thus target-specific
signal survives removal of the shared row axis, although target-wise
standardization lowers observed top-5 recovery relative to absolute scores.
These are weak aggregate retrieval results, not prospective target discovery.

## Exact boundary

Within each ligand, the two-way residual equals the column-centred score vector
minus one row-specific constant. Consequently its target order is exactly
identical to the column-centred score order. It need not equal the column-z order
(maximum rank difference =
{summary['rank_identity']['maximum_absolute_rank_difference']:.1f}). The rise in
spectral effective dimension after row centering can reveal residual covariance,
but row centering itself cannot create a new within-ligand ranking signal.

## Files

- `observed_metrics.csv`: aggregate estimates and paired-unit bootstrap intervals.
- `paired_contrasts.csv`: representation differences using identical bootstrap draws.
- `null_summary.csv`: frequency-multiset and binary fixed-margin null summaries.
- `analysis_summary.json`: configuration, hashes, counts, assertions, and diagnostics.
- `input_manifest.csv`: frozen input paths, hashes, and row counts.

Run from the package root:

```bash
.venv/bin/python analysis/residual_mie_boundary_audit.py
.venv/bin/python -m unittest analysis/test_residual_mie_boundary_audit.py
```

Bootstrap intervals are descriptive for the frozen support. The cluster bootstrap
resamples the pre-existing frozen Butina labels; it does not re-fit the original
clustering. The fixed-margin null uses degree-preserving double-edge swaps and
therefore preserves every compound active-count, every target frequency, and
binary incidence.
"""
    (output_dir / "README.md").write_text(text, encoding="utf-8")


def run_audit(
    scores_path: Path,
    activities_path: Path,
    output_dir: Path,
    config: AuditConfig,
) -> dict[str, Any]:
    """Execute the full audit and persist aggregate-only outputs."""

    score_usecols = [
        "ligand_id",
        "Cleaned SMILES",
        "Butina_clusters",
        *DOCK44,
    ]
    score_frame = pd.read_csv(scores_path, usecols=score_usecols)
    pairs = derive_strict_active_pairs(
        score_frame, activities_path, config.pchembl_threshold
    )
    representations, preprocessing = preprocess_score_representations(score_frame)
    selected_rows, incidence, cluster_labels, compound_degrees = active_incidence(
        score_frame, pairs
    )

    rank_matrices, identity_diagnostics = rank_score_representations(
        representations, selected_rows
    )
    value_matrices: dict[str, dict[str, np.ndarray]] = {}
    for name in REPRESENTATIONS:
        value_matrices[name] = metric_value_matrices(rank_matrices[name])

    maximum_rank_difference = float(
        identity_diagnostics["maximum_absolute_rank_difference"]
    )

    observed_metrics, paired_contrasts = run_bootstraps(
        value_matrices, incidence, cluster_labels, config
    )
    null_summary, null_diagnostics = run_null_models(
        value_matrices, incidence, config
    )

    target_degrees = incidence.sum(axis=0)
    represented_target_degrees = target_degrees[target_degrees > 0]
    _, cluster_counts = np.unique(cluster_labels, return_counts=True)
    summary: dict[str, Any] = {
        "analysis": "strict_frozen_chembl_active_target_residual_boundary_audit",
        "config": asdict(config),
        "input_derivation": {
            "activity_rule": (
                "frozen ChEMBL standard_relation '=' records; Ki/Kd/IC50/EC50; "
                "median pChEMBL per compound-target cell >= threshold"
            ),
            "molecular_join": "canonical InChIKey generated from frozen cleaned SMILES",
            "duplicate_rule": "one binary record per compound-target pair",
            "score_preprocessing": (
                "numeric coercion; positive scores clipped to zero; target-mean "
                "imputation; sample-SD target z-score"
            ),
            "tie_rule": "average within-ligand rank; lower score is favorable",
        },
        "benchmark_counts": {
            "score_matrix_compounds": int(len(score_frame)),
            "ranking_panel_targets": len(DOCK44),
            "active_pairs": int(incidence.sum()),
            "compounds": int(incidence.shape[0]),
            "represented_targets": int(np.sum(target_degrees > 0)),
            "butina_clusters": int(len(cluster_counts)),
            "active_targets_per_compound": compact_distribution_summary(
                compound_degrees
            ),
            "active_pairs_per_represented_target": compact_distribution_summary(
                represented_target_degrees
            ),
            "benchmark_compounds_per_butina_cluster": compact_distribution_summary(
                cluster_counts
            ),
        },
        "preprocessing_counts": preprocessing,
        "rank_identity": {
            "statement": (
                "within-ligand two-way-residual ranking equals column-centred ranking"
            ),
            "mathematical_reason": (
                "two_way_residual[i,j] = column_centred[i,j] - row_mean(column_centred)[i]"
            ),
            "floating_point_tie_policy": (
                "each representation is ranked independently; the two-way residual "
                "preserves the ordering of column-centred scores, not of column-z"
            ),
            "maximum_absolute_score_reconstruction_error": identity_diagnostics[
                "maximum_absolute_score_reconstruction_error"
            ],
            "maximum_absolute_rank_difference": maximum_rank_difference,
            "all_rankings_identical": identity_diagnostics["all_rankings_identical"],
        },
        "null_diagnostics": null_diagnostics,
        "privacy_boundary": {
            "row_level_records_written": False,
            "compound_identifiers_written": False,
            "target_identifiers_written": False,
            "aggregate_outputs_only": True,
        },
        "output_files": [
            "README.md",
            "analysis_summary.json",
            "input_manifest.csv",
            "observed_metrics.csv",
            "paired_contrasts.csv",
            "null_summary.csv",
        ],
    }

    output_dir.mkdir(parents=True, exist_ok=True)
    observed_metrics.to_csv(output_dir / "observed_metrics.csv", index=False)
    paired_contrasts.to_csv(output_dir / "paired_contrasts.csv", index=False)
    null_summary.to_csv(output_dir / "null_summary.csv", index=False)
    manifest = pd.DataFrame(
        [
            {
                "asset": "Docking-44 frozen score table",
                "package_relative_path": str(scores_path.resolve().relative_to(PACKAGE)),
                "sha256": sha256_file(scores_path),
                "rows": int(len(score_frame)),
            },
            {
                "asset": "frozen ChEMBL activity records",
                "package_relative_path": str(
                    activities_path.resolve().relative_to(PACKAGE)
                ),
                "sha256": sha256_file(activities_path),
                "rows": int(
                    len(pd.read_csv(activities_path, usecols=["pchembl_value"]))
                ),
            },
        ]
    )
    manifest.to_csv(output_dir / "input_manifest.csv", index=False)
    (output_dir / "analysis_summary.json").write_text(
        json.dumps(_json_safe(summary), indent=2, allow_nan=False) + "\n",
        encoding="utf-8",
    )
    write_readme(
        output_dir, summary, observed_metrics, paired_contrasts, null_summary
    )
    return summary


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--scores", type=Path, default=DEFAULT_SCORES)
    parser.add_argument("--activities", type=Path, default=DEFAULT_ACTIVITIES)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--pchembl-threshold", type=float, default=6.0)
    parser.add_argument("--bootstrap-replicates", type=int, default=5_000)
    parser.add_argument("--null-replicates", type=int, default=5_000)
    parser.add_argument("--switch-burnin-per-edge", type=int, default=20)
    parser.add_argument("--switch-between-per-edge", type=int, default=2)
    parser.add_argument("--seed", type=int, default=202_608_03)
    return parser.parse_args()


def main() -> None:
    """CLI entry point."""

    args = parse_args()
    config = AuditConfig(
        pchembl_threshold=args.pchembl_threshold,
        bootstrap_replicates=args.bootstrap_replicates,
        null_replicates=args.null_replicates,
        switch_burnin_per_edge=args.switch_burnin_per_edge,
        switch_between_per_edge=args.switch_between_per_edge,
        seed=args.seed,
    )
    summary = run_audit(
        scores_path=args.scores,
        activities_path=args.activities,
        output_dir=args.output_dir,
        config=config,
    )
    counts = summary["benchmark_counts"]
    print(
        "Residual/MIE boundary audit complete: "
        f"{counts['active_pairs']} pairs, {counts['compounds']} compounds, "
        f"{counts['represented_targets']}/{counts['ranking_panel_targets']} targets."
    )
    print(f"Aggregate outputs: {args.output_dir}")


if __name__ == "__main__":
    main()
